services:
  event-service:
    build:
      context: /EventService
      dockerfile: Dockerfile
    container_name: event-service
    ports:
      - "5264:8080"
    networks:
      - network
    environment:
      RABBITMQ_HOST: rabbitMQ
    depends_on:
      - mysql
      - rabbitMQ
    restart: always

  organization-service:
    build:
      context: /ServiceOrganization
      dockerfile: Dockerfile
    container_name: organization-service
    ports:
      - "5154:8080"
    networks:
      - network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=meetupnow;User Id=root;Password=admin;
    depends_on:
      - mysql
    restart: always

  email-service:
    build: /email-service
    container_name: email-service
    environment:
      RABBITMQ_HOST: rabbitMQ
      RABBITMQ_PORT: 5672
    ports:
      - "8082:8082"
    depends_on:
      - rabbitMQ
    networks:
      - network
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: meetupnow
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - network

  rabbitMQ:
    image: rabbitmq:3-management-alpine
    container_name: rabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - network
    restart: always

volumes:
  db-data:

networks:
  network:
    driver: bridge